"""create initial user api_key and audit_log tables

Revision ID: d08815a71a87
Revises:
Create Date: 2026-08-19 15:26:43.397560

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d08815a71a87"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
